version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:latest

    working_directory: ~/repo
    branches:
      ignore:
        - gh-pages
    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      # - run: npm run lint
      - run: npm run build:lib
      - run: npm run build:app
      # - run: CI=true npm test
