version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: node --version
      - run: npm --version
      #- run: npm install
      #- run: CI=true npm test
      #- run: npm run lint
