version: 2
jobs:
  build:
    docker:
      - image: trzeci/emscripten:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: node --version
      - run: npm --version
      - run: npm install
      # - run: npm run lint
      - run: npm run build:test
      - run: CI=true npm test
